---
- name: Install Archlinux desktop apps
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop:
    - syncthing
    - keepassxc
    - firefox
    - network-manager-applet
  become: yes

- name: Install blueman
  ansible.builtin.package:
    name: blueman
    state: latest
  tags: bluetooth
  become: yes

- name: Install sublime package feed key
  become: yes
  community.general.pacman_key:
    id: 1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Insert sublime package feed into pacman config
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [sublime-text]
      Server = https://download.sublimetext.com/arch/stable/x86_64

# Might report CHANGED if pacman cache is updated
- name: Install sublime text
  community.general.pacman:
    name: sublime-text
    state: latest
    update_cache: true
  become: yes
